language: c++
compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake .. && make

job:
  include:
    - stage: test
      script:
        - cd test
        - ./virtual_machine_run_test
